### ISSUE TITLE
Consider moving fossrit.github.io => foss.rit.edu

### ISSUE THREAD

**Issue by Tjzabel** [FOSSRIT/fossrit.github.io#113] opened 2020-03-05 22:53 UTC
At the moment, the old [FOSS website](https://magic.rit.edu/foss-init/) is outdated, and does not contain the current happenings with FOSS@MAGIC. 

That begs the question, is it worth (or politically possible) taking over the https://foss.rit.edu domain again?

**Comment by jwflory** [comment] 2020-03-06 12:37
To reply to this issue, I have two parts: what I think we should do in the best case scenario, and why we should do it this way.

## Redirect `foss.rit.edu` to `fossrit.github.io`

I need @itprofjacobs to comment on who has control of the `foss.rit.edu` domain and how we could go about making a request to set up a redirect. If it's as easy as opening an ITS ticket as a student employee, I can go ahead with that.

The preferred outcome I see is redirecting the `foss.rit.edu` domain to go to our new GitHub Pages website. This domain is linked widely around the web and has a **lot** of search engine juice too because it's been around for the better part of the last decade. Most of the content I added in the last week actually came from the temporary FOSS site that `foss.rit.edu` redirects to on the MAGIC website.

## Why this way?

One thing I realized the last few weeks going through all of our old content is that, sadly, RIT is not always a reliable provider of infrastructure and hosting. At one point, we had full control over the server where `foss.rit.edu` pointed, but that was yoinked from us some time in 2014. Now, the university is pushing away pretty hard on using subdomains for anything.

In the interest of "future-proofing" us to any other changes that RIT makes to hosting and infrastructure, I would prefer to use a domain or public address that we can have some reliance on for lasting well into the future. Given that Microsoft acquired GitHub and there are thousands if not hundreds of thousands of open source projects using GitHub Pages, I think it is safe to say that the GitHub domain is more reliable and trustworthy than something provided by the university.

So, the best case scenario I see is getting `foss.rit.edu` to redirect to `fossrit.github.io` since it gives us a big boost in discoverability and historical links across the web that use the old URL, but it doesn't create a dependency on RIT for letting us continue using a subdomain in an era where RIT does not want _any_ campus-affiliated group to use subdomains.

I hope this adds helpful context for why I think a redirect is the best outcome.

**Comment by ct-martin** [comment] 2020-03-06 16:09
IIRC, FOSS.rit.edu is owned (per say) by MAGIC and can be pointed to any server/computer physically on campus. To redirect we'd probably have to set up a server with a header set. Also, I think RIT likes off-site redirects even less than it does subdomains, FWIW.

**Comment by jwflory** [comment] 2020-03-07 21:59
I learned that this might actually be managed by ITS. I'm going to follow up with our ITS contact on Monday to see if he knows anything about it or if he can point me in the right direction.

**Comment by jwflory** [comment] 2020-03-09 20:20
Fantastic news! :tada: :tada: Our friends at ITS/CIAS set up a redirect for http://foss.rit.edu to the GitHub Pages site. I tested and confirmed this was a private browser window; if you are redirected to the old site, try clearing your browser cache.

Closing as complete! :cowboy_hat_face:

**Closed by jwflory** 2020-03-09 20:20 UTC
Labels: improvement, question
